name: attendance
description: An attendance app for KLE technological university students.

publish_to: 'none'


version: 1.1.3+8

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  sliding_up_panel: ^2.0.0+1
  shared_preferences: ^2.0.18
  after_layout: ^1.2.0
  url_launcher: ^6.1.10
  html: ^0.15.2
  http: ^0.13.5
  flutter_svg: ^2.0.9
  lottie: ^2.3.0
  provider: ^6.0.5
  shimmer: ^2.0.0
  rename: ^2.1.1
  flutter_windowmanager: ^0.2.0
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottieanimations/
